spring:
  application:
    name: open-log-investigator
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
        temperature: 0.1


investigator:
  logs:
    file-path: classpath:sample-logs/payment-logs.ndjson
